server:
  port: 8088
  
spring:
  datasource:
    url: jdbc:mysql://192.168.2.10:30306/testdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
